swagger: "2.0"
info:
  title: http2sample API
  description: API description of http2sample.
  version: 1.0.0
host: api.example.com
basePath: /dev
schemes:
  - https
tags:
  - name: test
    description: About test API

produces:
  - application/json

consumes:
  - application/json

paths:
  /http2sample/v1/api/test:
    get:
      summary: sample api.
      description: sample api.
      tags:
        - test
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/produceTestModel"
        400:
          description: Bad Request
          schema:
            $ref: "#/definitions/error"
      x-amazon-apigateway-integration:
        type: aws_proxy
        responses:
          default:
            statusCode: "200"
        uri: "arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:{Please replace with your IAM Account ID here.}:function:http2sample-dev/invocations"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
definitions:
  produceTestModel:
    type: object
    properties:
      message:
        type: "string"
  error:
    type: object
    properties:
      errorCode:
        type: "string"
      errorMessage:
        type: "string"
